{% set name = "PasteDeploy" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5f4b4d5fddd39b8947ea727161e366bf55b90efc60a4d1dd7976b9031d0b4e5f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - python >=3.7
    - setuptools

test:
  imports:
    - paste
    - paste.deploy

about:
  home: https://pylonsproject.org/
  license: MIT
  license_family: MIT
  license_file: license.txt
  summary: Load, configure, and compose WSGI applications and servers
  doc_url: https://docs.pylonsproject.org/projects/pastedeploy/
  dev_url: https://github.com/Pylons/pastedeploy

extra:
  recipe-maintainers:
    - lincrosenbach
    - kfasolin
    - synapticarbors
