travis:
  secure:
    BINSTAR_TOKEN: 1Sid5M8YZJCPuUa+CEinaoS8yOqdVMLXDMp0KUaEl83SeyOEI1MYC4sFetexdjHVQbfltcQFmNRxeRsISoaebNd3YsuV6nhWyNAc8DaqyeRcXYPGSNp1NVYb6ipOyLoFdXlyfU1SmMKg4k+GaPEJmhtGDC/zmNuLsGkeUDoOFqEN34kqgwsJvIFgIQdDSFi3fwmhKUckURW4hX0MBxLuV/q8ceNNK87b3OZQk/EkFQ5FWP4kY8FU8FwkGHj1NHNn9jRCP6NjOlgdVl4aH9eQx0ATUpaeOGemiir2xO/fotaP+7UM9RS4VeTmqjMxJpqaAAlV+OSEo1VjrN7RfribRb8gj7Lj5gplw8DrPIA8LowvIDWi2SADi6jtlG08Rm/wXeGmubaPHKRNVnpa0CYuPsh/N2On13YneDzYy2tQzTSiTR+EMOvEPkKTWMQ2gTBg0jEv1nPj05lI1V8wn1X7xf7AnAcjI4npJqJyMMpPk6zMO6Wkjb+HHLBzcrXa9rzaZ58KV80oqvMcVDl1Ahy6XEJvmTlARhCSmxoZUPqhDZLPyDrRK5kSanZM9Oc6QTzgF2GbPnB1M4t/TPVa6dzHPWjjdUMrES3M9AglU5ZspTUf6B+dQo6BUg9ZTHtsm3dc/ZzXIFyCz/3ASrL9oHuDSqOiiyQKnJ11WPm8tCeETOk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
